name: CoRe-env
channels:
 - conda-forge
dependencies:
  - python=3.9.1
  - r-base=4.0.2
  - r-nVennR=0.2.3         
  - r-magrittr=2.0.1
  - r-pheatmap=1.0.12      
  - r-tidyverse=1.3.0
  - r-cluster=2.1.1        
  - r-factoextra=1.0.7.999
  - r-devtools=2.3.2       
  - r-usethis=2.0.1
  - pip:
    - jsonpickle=2.0.0
    - matplotlib=3.3.4
    - networkx=2.5
    - numpy=1.20.1
    - pandas=1.2.3
    - pickle-mixin=1.0.2
    - pickleshare=0.7.5
    - scipy=1.6.2
    - seaborn=0.11.1
    - sklearn=0.0
